export const Team = [
  {
    name: 'Justin Mc Nary',
    id: 'dev00',
    email: 'jmcnary@redventures.com',
    type: 'front-end',
    kudos: false,
  },
  {
    name: 'Tom Zmyslo',
    id: 'dev1',
    email: 'tzmyslo@redventures.com',
    type: 'front-end',
  },
  {
    name: 'Bryan Chapman',
    id: 'dev2',
    email: 'bchapman@redventures.com',
    type: 'front-end',
    kudos: true,
  },
  {
    name: 'DUBB Sims',
    id: 'dev3',
    email: 'gwsims@redventures.com',
    type: 'front-end',
  },
  {
    name: 'Shaun Boehringer',
    id: 'dev4',
    email: 'sboehringer@redventures.com',
    type: 'front-end',
  },
  {
    name: 'Chas Vales',
    id: 'dev5',
    email: 'chvales@redventures.com',
    type: 'front-end',
  },
  {
    name: 'Joshua Soileau',
    id: 'dev50',
    email: 'jsoileau@redventures.com',
    birthdate: '09/15/1989',
    type: 'front-end',
  },
  {
    name: 'Ryan NESSY Van Ess',
    id: 'nessy',
    email: 'rvaness@redventures.com',
    type: 'front-end',
  },
  {
    name: 'Carlos Silva',
    id: 'backdev00',
    email: 'casilva@redventures.com',
    type: 'back-end',
  },
  {
    name: 'Ryan Weber',
    id: 'tank',
    email: 'rweber@redventures.com',
    type: 'back-end',
  },
];
